export const ACTION_TYPES = {
  FETCH_LOCATION_BY_PINCODE: "FETCH_LOCATION_BY_PINCODE",
  FETCH_LOCATION_BY_PINCODE_PENDING: "FETCH_LOCATION_BY_PINCODE_PENDING",
  FETCH_LOCATION_BY_PINCODE_FULFILLED: "FETCH_LOCATION_BY_PINCODE_FULFILLED",
  FETCH_LOCATION_BY_PINCODE_REJECTED: "FETCH_LOCATION_BY_PINCODE_REJECTED",

  FETCH_LOCATION_BY_PLACE: "FETCH_LOCATION_BY_PLACE",
  FETCH_LOCATION_BY_PLACE_PENDING: "FETCH_LOCATION_BY_PLACE_PENDING",
  FETCH_LOCATION_BY_PLACE_FULFILLED: "FETCH_LOCATION_BY_PLACE_FULFILLED",
  FETCH_LOCATION_BY_PLACE_REJECTED: "FETCH_LOCATION_BY_PLACE_REJECTED",
};
export const API_ENDPOINTS = {
  BASE_URL: "https://api.postalpincode.in/",
  FETCH_LOCATION_BY_PINCODE: "/pincode/",
  FETCH_LOCATION_BY_PLACE: "/postoffice/",
};
